# Generated by Django 6.0.3 on 2026-03-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='course_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AddField(
            model_name='post',
            name='instructor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
